services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5451:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=tlou
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: