version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DATABASE=tloupgdb
    volumes:
      - 'tloupgdb_pg_data:/bitnami/postgresql'


  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - 'tloupgdb_redis_data:/bitnami/redis/data'

volumes:
  tloupgdb_pg_data:
  tloupgdb_redis_data:

