services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5451:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=tlou
    volumes:
      - pgdata:/var/lib/postgresql/data

  # redis:
  #   image: bitnami/redis:latest
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - 'tloupgdb_redis_data:/bitnami/redis/data'

volumes:
  pgdata:
  # tloupgdb_redis_data: